// src/readme.js

import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { getFullProjectReadme } from './ai.js';

export async function updateReadme(currentDir, diff) {
    const readmePath = path.join(currentDir, 'README.md');

    try {
        if (await fs.pathExists(readmePath)) {
            const { confirmOverwrite } = await inquirer.prompt([{
                type: 'confirm',
                name: 'confirmOverwrite',
                message: chalk.yellow('README.md already exists. Do you want to REGENERATE the full professional documentation?'),
                default: false
            }]);

            if (!confirmOverwrite) {
                console.log(chalk.gray(' README update skipped by user.'));
                return false;
            }
        }

        console.log(chalk.cyan(' AI is architecting your professional README...'));
        
        const professionalContent = await getFullProjectReadme(diff);
        
        if (!professionalContent) {
            console.log(chalk.red(' AI failed to generate content.'));
            return false;
        }

        await fs.writeFile(readmePath, professionalContent + `\n\n---\n*Generated by GitReady AI*`);
        
        return true;
    } catch (error) {
        console.error(chalk.red(` README Error: ${error.message}`));
        return false;
    }
}