// src/readme.js

import fs from 'fs-extra';
import path from 'path';
import {
    getAIReadmeSummary,
    getInitialReadmeContent
} from './ai.js';

export async function updateReadme(currentDir, diff) {
    const readmePath = path.join(currentDir, 'README.md');

    try {
        // Existing README
        if (await fs.pathExists(readmePath)) {

            const summary = await getAIReadmeSummary(diff);

            // AI unavailable
            if (!summary) {
                console.log(
                    ' README update skipped (AI unavailable).'
                );
                return false;
            }

            const updateSection = `
            
### Latest Updates (${new Date().toLocaleDateString()})

- ${summary}
`;

            await fs.appendFile(readmePath, updateSection);

            return true;
        }

        // New README
        const fullContent =
            await getInitialReadmeContent(diff);

        // AI unavailable
        if (!fullContent) {
            console.log(
                ' README generation skipped (AI unavailable).'
            );
            return false;
        }

        await fs.writeFile(
            readmePath,
            `${fullContent}

---
*Generated by GitReady AI*
`
        );

        return true;

    } catch (error) {
        console.log(
            ` README operation failed: ${error.message}`
        );

        return false;
    }
}