import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { getAIReadmeSummary, getInitialReadmeContent } from './ai.js';

export async function updateReadme(currentDir, diff) {
    const readmePath = path.join(currentDir, 'README.md');

    try {
        // CASE 1: Updating existing README
        if (await fs.pathExists(readmePath)) {
            const summary = await getAIReadmeSummary(diff);

            if (!summary) {
                console.log(chalk.yellow(' ℹ️  README update skipped (AI unavailable).'));
                return false;
            }

            // Clean formatting for Markdown append
            const updateSection = `\n\n### 🚀 Latest Updates (${new Date().toLocaleDateString()})\n- ${summary}`;
            
            await fs.appendFile(readmePath, updateSection);
            return true;
        }

        // CASE 2: Creating new README
        const fullContent = await getInitialReadmeContent(diff);

        if (!fullContent) {
            console.log(chalk.yellow(' ℹ️  README generation skipped (AI unavailable).'));
            return false;
        }

        const finalReadme = `${fullContent}\n\n---\n*Generated by GitReady AI*`;
        await fs.writeFile(readmePath, finalReadme);

        return true;

    } catch (error) {
        console.log(chalk.red(` ❌ README operation failed: ${error.message}`));
        return false;
    }
}